#!/usr/bin/env bash

echo +cd ~ewen/www/loca7.ewen.works
cd ~ewen/www/loca7.ewen.works
echo checking for updates...
if [ $(git fetch origin --quiet; git rev-list HEAD..@{u} --count) -le 0 ]; then
  echo already up to date.
  exit 0
else
  echo updates found.
fi
echo +git pull
git pull
echo +pnpm i
pnpm i
echo +pnpm build
pnpm build
echo +pnpm prisma migrate deploy
pnpm prisma migrate deploy
echo +rm -r build/client/photos
rm -r build/client/photos
echo '+ln -s `realpath public/photos` `realpath build/client/photos`'
ln -s `realpath public/photos` `realpath build/client/photos`
echo +pm2 restart loca7
pm2 restart loca7
